spring:
  profiles:
    active:
      - cat
      - ES
      - dev
guru:
  username: YmlUserName
  password: YmlSecretPassword
  jdbcurl: YmlJDBCUrl

---
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl
spring:
  config:
    activate:
      on-profile: prod
